export const teori = [{
    title:'Ken Angrok',
    content:`<p>Ken Angrok adalah raja pertama sekaligus pendiri Kerajaan Singhasari. Ia bergelar Sri Rajasa Sang Amurwwabhumi. Dalam Kitab Nagarakratagama, Ken Angrok dikenal sebagai Bathara Girinathaputra atau putra Sri Girinatha (Poesponegoro dan Notosusanto, 1984). Sedang dalam Kitab Pararaton, Ken Angrok diceritakan sebagai anak dari pasangan petani bernama Ken Endok dan Gajahpara. Keduanya tinggal di Desa Pangkur, sebelah timur Gunung Kawi. Dalam perjalanan mengantar makanan untuk suaminya, Ken Endok dikisahkan bertemu dengan Dewa Brahma di Tegal Lalateng dan akhirnya mengandung. Dewa Brahma mengatakan bahwa anak yang dikandung Ken Endok kelak akan menjadi raja di Pulau Jawa. Tiba ketika Ken Angrok lahir, Ken Endok membuang bayinya itu di kuburan. Seorang pencuri bernama Lembong kemudian menemukannya dan merawat Ken Angrok hingga besar. Oleh karena ia diasuh oleh seseorang yang tidak elok perilakunya, Ken Angrok kemudian ikut tumbuh menjadi orang yang sering berbuat jahat seperti mencuri, merampok, membunuh dan sebagainya.</p><br/>
    <p>Atas bantuan seorang brahmana bernama Danghyang Lohgawe, Ken Angrok kemudian bisa menjadi prajurit dari akuwu Tumapel yakni Tunggul Ametung, yang saat itu memerintah di wilayah Ken Angrok tinggal. Namun ternyata, Ken Angrok jatuh hati pada istri Tunggul Ametung yang bernama Ken Dedes karena parasnya yang rupawan. Ia pun membunuh Tunggul Ametung dengan keris buatan Mpu Gandring, dan dengan berbagai cara yang sangat rapi, ia dapat menggantikan posisi Tunggul Ametung dan memperistri Ken Dedes. Poesponegoro dan Notosusanto (1984: 427) menjelaskan bahwa dari pernikahannya dengan Ken Dedes, Ken Angrok memiliki empat anak yakni Mahisa Wonga Teleng, Panji Saprang, Agnibhaya dan Dewi Rimbu. Ken Angrok juga memiliki satu istri lain bernama Ken Umang. Dari Ken Umang, ia juga memiliki empat orang anak yakni Panji Tohjaya, Panji Sudhatu, Panji Wregola dan Dewi Rambu. Ken Angrok kemudian menjadi raja Tumapel dan bergelar Sri Rajasa Sang Amurwwabhumi. Setelah menjadi raja, Ken Angrok  menaklukan Kerajaan Daha (Kadiri) pada tahun 1144 Saka (1222 Masehi). Ia pun menjadi maharaja di Tumapel dengan wilayah kekuasaan yang besar. Ken Angrok kemudian wafat di tahun 1169 Saka (1247 Masehi) setelah dibunuh oleh orang suruhan Anusapati, anak tirinya.</p>
    `,
    image:null
},
{
    title:'Anuspati',
    content:`<p>Anusapati merupakan raja kedua yang memerintah Kerajaan Singhasari sepeninggal Ken Angrok. Adapun hubungan keluarga antara Anusapati dan Ken Angrok adalah anak dan ayah tiri. Anusapati adalah anak kandung dari Ken Dedes dan Tunggul Ametung. Turaeni (2015: 136) menyebutkan bahwa Anusapati juga dikenal sebagai Panji Anengah. Setelah mengetahui Ken Angrok adalah orang yang membunuh ayahnya, ia memerintahkan seseorang untuk membunuh Ken Angrok. Setelah kejadian tersebut, Anusapati menjabat sebagai raja Singhasari.</p><br/>
    <p>Lama pemerintahan Anusapati dijelaskan berbeda pada Kitab Pararaton dan Kitab Nagarakrtagama. Kitab Pararaton terjemahan Hardjowardojo (1965: 32-33) menyebutkan bahwa pemerintahan Anusapati berjalan sejak 1247 M sampai 1249 M, hanya dua tahun. Sementara itu Poesponegoro dan Notosusanto (1984) menyebutkan bahwa pada Kitab Nagarakrtagama, dijelaskan Anusapati menjabat sebagai raja Singhasari selama dua puluh satu tahun, sejak tahun 1227 M sampai 1248 M. Perihal kejadian-kejadian penting selama masa pemerintahan Anusapati tidak banyak diketahui. Jika dilihat dari terjemahan Kitab Pararaton, Anusapati dikenal memiliki hobi mengadu ayam. Di tahun 1248 M, Anusapati dibunuh oleh Panji Tohjaya, yang merupakan anak kandung dari Ken Angrok dengan Ken Umang. Anusapati kemudian didharmakan di Kidal.</p><br/>
    <p>Selanjutnya, tokoh yang banyak diketahui menggantikan kedudukan Anusapati sebagai raja Singhasari adalah Tohjaya. Meski demikian, ada referensi lain yang menyebutkan cerita berbeda. Poesponegoro dan Notosusanto (1984) dalam bukunya yang berjudul Sejarah Nasional Indonesia Jilid 2 menjelaskan, di dalam prasasti Mula-Malurung Tohjaya disebutkan tidak menggantikan Anusapati, melainkan menggantikan Nararyya Gunging Bhaya. Adapun Gunging Bhaya dan Tohjaya disebutkan sebagai paman dari Nararyya Smining Rat, yang kemudian diketahui bahwa itu merupakan nama lain dari Wisnuwardhana. Prasasti Mula-Malurung juga menyebutkan bahwa Gunging Bhaya menjabat sebagai Raja Singhasari setelah menggantikan Bhatara Parameswara. Meski belum ada kepastian tepat mengenai siapa Bhatara Parameswara itu, dapat dikatakan bahwa Tohjaya bukan raja pengganti Anusapati, melainkan menggantikan adik dari Anusapati yakni Nararyya Gunging Bhaya. Tohjaya menjabat hanya beberapa bulan, sebelum kemudian ia meninggal terkena luka tombak dalam pemberontakan orang-orang Rajasa dan selir yang menyerbu istana. Ia dicandikan di Katanglumbang.</p>`,
    image:[{name:'Candi Kidal', url:'https://tugujatim.id/wp-content/uploads/2021/04/IMG_20210415_195900-mini.jpg'}]
},
{
    title:'Wisnuwarddhana',
    content:`<p>Raja selanjutnya yang menggantikan Tohjaya adalah Wisnuwardhhana, atau yang memiliki nama asli Rangga Wuni. Ia adalah anak dari raja kedua Singhasari yakni Anusapati. Nama Wisnuwarddhana mulai disematkan ketika ia dinobatkan menjadi raja Singhasari pada 1248 M dengan gelar Sri Jayawisnuwarddhana. Bersama Mashisa Cempaka, cucu Ken Angrok dari Ken Dedes yang memiliki gelar Narasingh, Wisnuwarddhana memerintah Singhasari seperti dua ekor ular dalam satu lubang (Poesponegoro dan Notosusanto, 1984: 430). Dalam prasasti Mula-Malurung, Wisnuwarddhana disebutkan memiliki gelar Nararyya Smining Rat dan memiliki istri bernama Nararyya Waning Hyun. Nararyya Smining Rat disebutkan menggantikan Nararyya Tohjaya sebagai raja Singhasari.</p><br/>
    <p>Sepanjang hidupnya, Wisnuwarddhana diketahui telah mengeluarkan beberapa prasasti, diantaranya Prasasti Mula-Malurung di Desa Mula dan Malurung pada tahun 1255 M, dan prasasti Maribong di Desa Maribong pada tahun 1264 M. Adapun prasasti lain yang menyebutkan Wisnuwarddhana adalah prasasti Pakis Wetan berangka tahun 1267 yang dikeluarkan oleh Kertanegara (Poesponegoro dan Notosusanto, 1984: 431-433). Menurut Kitab Nagarakrtagama, Wisnuwarddhana meninggal di tahun 1268 M dan dicandikan di Candi Mleri, Blitar dan Candi Jago, Malang.</p>
    `,
    image:[{name:'Candi Mleri',url:'https://res.cloudinary.com/purnama/images/w_525,h_350/f_auto,q_auto/v1587080192/Candi-Mleri1/Candi-Mleri1.jpg'},{name:'Candi Jago',url:'https://www.pegipegi.com/travel/wp-content/uploads/2018/10/candi-jago-malang.jpg'}]
},
{
    title:'Kertanegara',
    content:`<p>Kertanegara merupakan anak dari raja ketiga Singhasari, Wisnuwarddhana. Kertanegara telah dinobatkan menjadi rajamuda atau yuwaraja pada tahun 1254 M ketika ayahnya masih hidup. Hal ini juga sesuai dengan isi pada prasasti Mula-Malurung. Ketika sang ayah masih hidup, Kertanegara yang telah menjadi raja muda juga ikut memimpin Singhasari dengan tetap dibimbing oleh Wisnuwarddhana. Pada setiap prasasti yang dikeluarkan oleh Kertanegara sebelum tahun 1268 M, selalu ada istilah makamangalya di dalamnya. Poesponegoro dan Notosusanto (1984: 432) menjelaskan bahwa istilah makamangalya diterjemahkan sebagai “di bawah pengawasan” atau “dengan bimbingan”. Barulah setelah sepeninggal Raja Wisnuwarddhana, prasasti yang dikeluarkan Kertanegara tidak lagi mencantumkan istilah makamangalya, yang artinya ia telah resmi menjadi raja utama Singhasari.</p><br/>
    <p>Raja Kertanegara dikenal sebagai raja yang sangat pintar dalam bidang politik dan agama. Berbagai kebijakan yang dilakukan semasa hidupnya membawa Singhasari kepada puncak kejayaan. Salah satu kebijakannya yang paling terkenal adalah pelaksanaan ekspedisi Pamalayu, untuk menaklukan Malayu di tahun 1275 M (Poesponegoro dan Notosusanto, 1984: 437). Dalam bukunya, Poesponegoro dan Notosusanto juga menjabarkan bahwa  pada tahun 1284 Kertanegara berhasil menaklukan Bali. Hampir seluruh wilayah Indonesia berhasil tunduk di bawah pemerintahan Kertanegara dari Singhasari, wilayah-wilayah itu antara lain adalah Semenanjung Tanah Melayu, seluruh Jawa, Sumatera, Kalimantan dan Indonesia bagian Timur. Kekuasaan Singhasari yang sangat besar dan luas itu menjadi terkenal hingga terdengar sampai Kekaisaran Mongol, yang kemudian menjadikan Kubhilai Khan, pemimpin Kekaisaran Mongol berusaha untuk menaklukan tanah Jawa.</p><br/>
    <p>Pemerintahan Kertanegara berakhir pada tahun 1292 M setelah Singhasari diserang oleh Jayaktwang dari Kediri. Menurut Kidung Harsa Wijaya (dalam Poesponegoro dan Notosusanto, 1984: 443) Jayakatwang menyerang Singhasari atas dasar alasan balas dendam akan perbuatan para leluhur Kertanegara di masa lalu. Jayakatwang sendiri adalah keturunan dari raja Kertajaya, atau dikenal juga dengan nama Dandang Gendhis yang dahulu telah meninggal karena dibunuh oleh Ken Angrok, leluhur dari Kertanegara. Meski Kertanegara dan Jayakatwang sebenarnya telah menjadi keluarga oleh karena saudara perempuan Kertanegara merupakan istri dari Jayakatwang, namun itu tidak mengurangi tekad Jayakatwang untuk menaklukan kerajaan Singhasari. Dengan kemenangan Jayakatwang itu, Singhasari telah dianggap runtuh dan tunduk pada kerajaan Kediri. Kertanegara kemudian dicandikan di Singhasari dan di Pasuruan Jawa Timur (Candi Jawi).</p>
    `,
    image:[{name:'Candi Singosari', url:'https://jejakpiknik.com/wp-content/uploads/2017/10/@yovi_507.jpg'},{name:'Candi Jawi',url:'https://t-2.tstatic.net/tribunnewswiki/foto/bank/images/candi-jawi-jawa-timur.jpg'}]
}
]