import sumberair from './assets/sumberair.png';
import tamanarca from './assets/tamanarca.jpg';
import pohonarca from './assets/pohonarca.jpg';
import singosari1 from './assets/singosari1.jpg';
import singosari2 from './assets/singosari2.jpg';
import singosari21 from './assets/singosari21.jpg';
import singosari3 from './assets/singosari3.jpg';
import singosari4 from './assets/singosari4.jpg';
import ArcadwarapalaNorth from './assets/arcanorth.jpg'
import ArcadwarapalaSouth from './assets/arcasouth.jpg'
export const statues=[
    {
        title: "Candi Kidal",
        description:"Candi Kidal adalah salah satu peninggalan kerajaan Singhasari yang berlokasi di Desa Kidal, Kecamatan Tumpang, Kabupaten Malang, Jawa Timur. Candi ini merupakan tempat didharmakannya raja kedua Singhasari, yakni Anusapati. Candi Kidal pertama kali dilaporkan oleh B. de Haan dan J. F. G. Brumund pada tahun 1926 (Lutfi Ismail, dkk, 2018). Bangunan Cagar Budaya Candi Kidal berdenah bujur sangkar, dengan sisi-sisi berukuran 8,36 meter, memiliki penampil dan tangga masuk di bagian barat. Peninggalan ini memiliki sisi menarik yang sering dijadikan alasan oleh para pengunjung mendatanginya. Hal ini terletak pada relief candi yang masih terlihat jelas hingga kini. Pada permukaan dinding candi, terdapat relief kisah Garudeya (Garuda) yang memperjuangkan untuk mendapatkan tirta amertha sebagai penebusan ibunya dari perbudakan sang Kadru. Cara membaca relief adalah dengan berjalan berlawanan arah jarum jam, dimulai dari sisi sebelah selatan. Relief pertama menggambarkan Garuda menggendong 3 ekor ular besar, relief kedua menggambarkan Garuda dengan kendi di atas kepala, sementara relief ketiga Garuda menyangga seorang perempuan (diketahui bahwa sosok perempuan itu adalah ibunya, Winata). Di antara ketiga relief tersebut, relief kedua adalah yang paling utuh.",
        images: [{name:'Candi Kidal', sumber:'https://tugujatim.id/', url:'https://tugujatim.id/wp-content/uploads/2021/04/IMG_20210415_195900-mini.jpg'},{name:'Garudeya', sumber:'https://m.merdeka.com/', url:'https://rri.co.id/__srct/cfb3228334b52d754373c1e819e9a6cc/1155189/28a6dcbd234a02dc74feeab65acf382d.jpg'}]
    },
    {
        title: "Candi Jago",
        description:"Candi Jago merupakan candi yang terletak di daerah Tumpang, Malang, Jawa Timur. Candi ini juga merupakan salah satu peninggalan Kerajaan Singhasari, tepatnya merupakan tempat pendharmaan Raja Wisnuwarddhan. Pada sekeliling candi, terdapat sebuah arca yang dikenal sebagai nama Amoghapasa, bentuk Awalokiteswara bertangan delapan, dengan pengikutnya (Poesponegoro dan Notosusanto, 1984: 435).  Terdapat pula arca-arca lain seperti Bhairawa. Beberapa relief penting juga terdapat pada candi ini, diantaranya adalah relief Tantri Kamandaka, relief Ari Dharma, relief Kunjarakarna, relief Parthayajna, relief Ar-junawiwaha, dan relief Kresnayana (Lutfi Ismail, dkk, 2018: 181). Setiawan & Setiawati (2019: 144) menjabarkan detail keseluruhan bangunan Candi Jago. Candi ini berbentuk segi  empat dengan  ukuran 23  m  x  14  meter. Bangunan  candi  menghadap  ke  barat.  Candi  ini  berdiri  di  atas  batur  (alas),  setinggi sekitar satu  meter dan kaki candi  yang  terdiri atas 3 teras bertingkat.  Teras kaki candi berbentuk  semakin  kecil  ke  bagian  atas.  Pada  lantai  pertama  terdapat  selasar  yang dapat dilewati untuk mengelilingi candi. Candi  Jago didirikan sekitar  tahun  1268-1280  M (Setiawan & Setiawati, 2019). Candi  tersebut dibangun   sebagai   penghormatan   kepada   Sri   Jaya   Wisnuwardana.   Candi    Jago merupakan  salah  satu  peninggalan  kerajaan  Singasari  dan  bercorak  Hindu  Budha. Adapun sisi menarik dari Candi Jago adalah keunikan relief mereka yang menggambarkan cerita fabel (hewan).",
        images: [{name:'Candi Jago', sumber:'https://www.pegipegi.com/',url:'https://www.pegipegi.com/travel/wp-content/uploads/2018/10/candi-jago-malang.jpg'},{name:'Relief Mahabharata', sumber:'https://ngalam.co/', url:'https://ngalam.co/wp-content/uploads/2017/02/potongan-relief-Mahabharata-di-Candi-Jago.jpg'},{name:'Relief Fabel', sumber:'https://sejarahlengkap.com/', url:'https://sejarahlengkap.com/wp-content/uploads/2018/10/Relief-Fabel-candi-jago.jpg'},{name:'Relief Kresnayana', sumber:'https://ngalam.co/',url:'https://ngalam.co/wp-content/uploads/2017/02/relief-Kresnayana-di-candi-Jago.jpg'}]
    },
    {
        title: "Candi Singosari",
        description: "Candi Singosari merupakan tempat pendharmaan untuk raja termahsyur Singhasari, yakni raja Kertanegara. Candi ini berlokasi di Desa Candirenggo, Kecamatan Singosari, Kabupaten Malang, Jawa Timur. Candi ini pertama kali dilaporkan oleh Nicolaus Engelhardt pada tahun 1803, yang kemudian dikenal dengan nama Candi Singosari (Kemendikbud, Website Cagar Budaya). Pada tahun 1804 dilakukan pemindahan arca - arca dari reruntuhan candi, arca - arca tersebut dibawa ke negeri Belanda pada tahun 1819. Pembangunan candi dimaksudkan untuk memperingati wafatnya Raja Kertanegara beserta para pejabat tinggi Singhasari (1292 M). Dilansir melalui Perpusnas ID, tubuh candi berdiri di atas batur kaki setinggi sekitar 1,5 m, tanpa hiasan atau relief pada kaki candi. Tangga naik ke selasar di kaki candi tidak diapit oleh pipi tangga dengan hiasan makara seperti yang terdapat pada candi-candi lain. Pintu masuk ke ruangan di tengah tubuh candi menghadap ke selatan, terletak pada sisi depan bilik penampil (bilik kecil yang menjorok ke depan). Pintu masuk ini terlihat sederhana tanpa bingkai berhiaskan pahatan. Di atas ambang pintu terdapat pahatan kepala Kala.",
        images: [{name:'Candi Singosari', sumber:'https://www.obsessionnews.com/', url:'https://www.obsessionnews.com/wp-content/uploads/2019/09/Candi-Singosari.jpg'},]
    },
    {
        title: "Arca Dwarapala",
        description:"Arca Dwarapala merupakan salah satu arca terbesar di Indonesia. Arca ini berjumlah dua arca dengan bentuk tubuh yang berukuran besar dan ekspresi yang cukup menakutkan. Dwarapala Singhasari ini terletak hanya sekitar 200 m dari letak candi Singosari, sehingga dapat dikatakan bahwa arca ini masih satu kompleks dengan candi tersebut. Arca ini juga ditemukan oleh Nicolaus Engelhardt pada tahun 1803, bersamaan ketika beliau menemukan Candi Singosari.   Dua arca yang dibuat dari batu monolitik tersebut memiliki ketinggian 3,70 meter (Mulyadi, dkk, 2015: 38). Sejatinya arca Dwarapala memang merupakan patung penjaga sebelum memasuki wilayah kerajaan. Hal ini sesuai dengan lokasi ditemukannya arca yang berada di sekitar Candi Singosari. Arca yang berada di selatan jalan yang menghadap ke utara posisi tangan kanan memegang gada, sedangkan tangan kiri diletakkan di lutut dengan kondisi berjongkok. Sementara itu, untuk arca yang menghadap selatan, tangan kanannya memberikan kode dua jari, sedangkan tangan kirinya memegang gada yang dibalik. Selain fungsinya yang merupakan patung penjaga, arca ini juga berfungsi untuk mengingatkan rakyat rajin beribadah.",
        images: [{name:'Arca Dwarapala',sumber:'Dokumentasi Pribadi',url:ArcadwarapalaNorth},{name:'Arca Dwarapala',sumber:'Dokumentasi Pribadi',url:ArcadwarapalaSouth}]
    },
    {
        title: "Candi Sumberawan",
        description: "Candi Sumberawan merupakan salah satu peninggalan masa Kerajaan Singhasari. Lokasi candi ini ada di Dusun Sumberawan, Desa Toyomarto, Kecamatan Singosari, Kabupaten Malang. Candi ini pernah dipugar pada sekitar tahun 1937 (Sudikno & Surjono, 2017).  Saat pemugaran berlangsung, terdapat sumber air tepat di bawah candi. Lama kelamaan, aliran airnya jadi merembes ke mana-mana dan mengakibatkan muncul sumber air baru di sekitar candi. Pada candi ini tidak ditemukan relief, arca atau benda lain selain badan candi. Ukuran bagian dasar candi adalah 6,25m x 6,25m dan tinggi 5,23m. Bangunan ini terbuat dari bahan material batu Andesit. Lokasinya berada di kawasan kaki gunung Arjuno dengan ketinggian 650 meter dari permukaan laut, sehingga suasananya cukup nyaman dan asri. Adapun sumber air yang berada di sekitar candi kini ramai didatangi pengunjung dan penduduk sekitar. Masyarakat percaya bahwa air itu merupakan air suci dan bila seseorang membasuh muka menggunakan air itu maka mereka akan awet muda. Kepercayaan itu dipercaya hingga kini dan menyebabkan ramainya area sumber air.",
        images: [{name:'Candi Sumberawan',sumber:'https://www.puteramentari.com/',url:'https://www.puteramentari.com/wp-content/uploads/2020/07/Candi-Sumberawan-Stupa-di-Jawa-Timur.jpg'}]
    }
]

export const kondisi = [
    {
        title:'Candi Singosari',
        description:"Situs peninggalan Kerajaan Singhasari ini kini dijadikan sebagai objek wisata sejarah untuk para wisatawan, baik wisatawan lokal maupun non-lokal. Oleh karena dijadikan sebagai tempat wisata, di sekeliling candi ditemukan banyak toko kecil dan penjual keliling yang setiap pagi selalu siap sedia menyambut para pengunjung. ",
        images:[{name:'Tampak Depan',sumber:'Dokumentasi Pribadi',url:singosari1},{name:'Pedagang sekitar candi',sumber:'Dokumentasi Pribadi',url:singosari2},{name:'Pedagang sekitar candi',sumber:'Dokumentasi Pribadi',url:singosari21},{name:'Toko depan candi',sumber:'Dokumentasi Pribadi',url:singosari3},{name:'Penunjuk jalan',sumber:'Dokumentasi Pribadi',url:singosari4}]
    },
    {
        title:'Arca Dwarapala',
        description:"Lokasi Arca Dwarapala hanya berjarak sekitar 200m dari Candi Singosari. Di sekitar situs ini tidak terdapat toko-toko maupun penjual keliling seperti yang ada di sekitar Candi Singosari. Rumah-rumah warga berada tepat mengelilingi situs Arca Dwarapala, sehingga keberadaan situs ini berada di tengah perumahan warga setempat. Kedua Arca Dwarapala ini berada masing-masing di tepi jalan dengan dibatasi oleh taman luas dan pagar pembatas. Adapun di luar pagar sudah berhadapan langsung dengan rumah-rumah warga. ",
        images:[{name:'Arca Dwarapala',sumber:'Dokumentasi Pribadi',url:ArcadwarapalaSouth},{name:'Taman di sekeliling',sumber:'Dokumentasi Pribadi',url:tamanarca},{name:'Pohon-pohon di sekitar',sumber:'Dokumentasi Pribadi', url: pohonarca},{name:'Arca Dwarapala',sumber:'Dokumentasi Pribadi',url:ArcadwarapalaNorth}]
    },
    {
        title:'Candi Sumberawan',
        description:"Candi Sumberawan merupakan salah satu situs yang unik. Candi ini tidak memiliki relief maupun arca di di dalamnya, sehingga bangunan candi ini hanya berbentuk stupa saja. Meski demikian, area situs ini tetap ramai dikunjungi pengunjung. Sebagian besar pengunjung yang datang ke sini adalah untuk melihat telaga atau sumber air yang ada di sekitar candi. Masyarakat sekitar percaya bahwa air yang muncul dari situ adalah air suci.",
        images:[{name:'Candi Sumberawan',sumber:'https://www.puteramentari.com/',url:'https://www.puteramentari.com/wp-content/uploads/2020/07/Candi-Sumberawan-Stupa-di-Jawa-Timur.jpg'},{name:'Sumber Air Suci', sumber:'JESIAMAR',url: sumberair}]
    },
]